In [18]:
"""
Basics of vannila neural network.

Based on Sentdex's neural network playlist: https://www.youtube.com/playlist?list=PLQVvvaa0QuDcjD5BAw2DxE6OF2tius3V3
"""

"\nBasics of vannila neural network.\n\nBased on Sentdex's neural network playlist: https://www.youtube.com/playlist?list=PLQVvvaa0QuDcjD5BAw2DxE6OF2tius3V3\n"

In [37]:
import numpy as np  

from typing import List

In [46]:

n_input_layer = 4
n_neurons = 3

# initially weights have to be random within some range, the lesser the range the better.
# 3 sets of weights, with each having len(x) columns.
activation = np.array([1, 2, 3, 4.5])
weights    = np.array(np.random.rand(n_neurons, n_input_layer))
biases     = np.array([4, 5, 6])

print(f"activation = {activation}\n")
print(f"weights = {weights}\n")
print(f"biases = {biases}\n")

activation = [1.  2.  3.  4.5]

weights = [[0.13786524 0.08911181 0.17372108 0.31248231]
 [0.83691474 0.78526225 0.32430536 0.08954182]
 [0.09672035 0.74665453 0.36129682 0.72485405]]

biases = [4 5 6]



In [47]:
"""
The input layer has 4 neurons
The next layer has 3 neurons

for every neuron perform => Y = (weight * activation) + bias
"""

# Simulating a single forward pass.
# for every neuron in the input layer.
    # get the respective weights and biases of the neuron for next layer
    # multiply weights and activation and add bias


output_array: List[float] = []

for n in range(n_neurons):
    current_weight_set = weights[n]
    current_bias = biases[n]

    current_output = 0

    for a, w in zip(activation, current_weight_set):
        current_output += w * a
    
    current_output += current_bias
    output_array.append(current_output)

print(np.array(output_array))


[ 6.24342252  8.78329351 11.93576311]


In [48]:
# Simulating simple single forward pass with numpy dot product.

output_array = np.dot(weights, activation) + biases
print(np.array(output_array))

[ 6.24342252  8.78329351 11.93576311]


In [49]:
# We used a single set of activation.
# Ideally, we would have several batches of them.

n_neurons = 3
n_activation = 4


activation_set = [
    [1, 2, 3, 4], 
    [2.2, 5.2, 1, 5.5], 
    [6.3, 1, 5, 6]
]

weight_set = np.random.rand(n_neurons, n_activation)
biases = np.zeros(n_neurons)

print(f"activation = {np.array(activation_set)}\n")
print(f"weights = {np.array(weight_set)}\n")
print(f"biases = {np.array(biases)}\n")

activation = [[1.  2.  3.  4. ]
 [2.2 5.2 1.  5.5]
 [6.3 1.  5.  6. ]]

weights = [[0.30559297 0.2884694  0.10262371 0.04040817]
 [0.23676885 0.52056363 0.11930513 0.17289563]
 [0.59867979 0.60765936 0.58573447 0.0369572 ]]

biases = [0. 0. 0.]



In [44]:
# Simulating forward pass with batch inputs.

# for every neuron
    # pick the current activation batch
    # process the activation batch for every weight_set


output_array: List[List[float]] = []

for n in range(n_neurons):
    current_activation    = activation_set[n]
    current_bias          = biases[n]
    current_neuron_output = []

    for current_weights in weight_set:
        
        output = 0
        
        for a, w in zip(current_activation, current_weights):
            output += a * w

        output += current_bias
        current_neuron_output.append(output)
    
    output_array.append(current_neuron_output)

print(np.array(output_array))


[[ 6.17949219  6.14209142  6.3069362 ]
 [ 8.32494286  9.57070274  7.46557765]
 [ 8.11313258 10.39524648 10.11814745]]


In [45]:
# Simulating forward pass with batch inputs. (numpy dot product).

output_array = np.dot(activation_set, np.array(weight_set).T) + biases 
print(output_array)

[[ 6.17949219  6.14209142  6.3069362 ]
 [ 8.32494286  9.57070274  7.46557765]
 [ 8.11313258 10.39524648 10.11814745]]
